version: "2"
engines:
  eslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
checks:
  method-complexity:
    enabled: false
  identical-code:
    config:
      threshold: 5

ratings:
  paths:
  - lib/**
